### ISSUE TITLE
npm install being run on non-existent duplicated subfolder

### ISSUE THREAD

**Issue by brandonscript** [tusbar/grunt-subgrunt#28]
Not really sure what is going on here; `--verbose` doesn't seem to offer any additional information, but hopefully I can figure out what's going on.

I've got a gruntfile like so:

    grunt.initConfig({
        subgrunt: {
            myTarget: {
                options: {
                    npmInstall: true
                },
                projects: {
                    'node_modules/another-grunt-project: [ 'default',  '--assets=' + require('path').resolve() ]
                }
            }
        }
    })

For some reason, when I set npmInstall to true, it's duplicating the path:

    npm WARN ENOENT ENOENT: no such file or directory, open 
    '/Users/Me/Development/parent-project/node_modules/another-grunt-project/node_modules/another-grunt-project/package.json'
                                                               ^                                  ^ 
    >> Installed node modules in "node_modules/another-grunt-project"

Could this be related to something funky in my subproject? I'm not adjusting `base` at all, and `process.cwd()` on the subproject outputs:

    >> /Users/Me/Development/parent-project/node_modules/another-grunt-project

If not, is there an (undocumented) way of overwriting the path to package.json?

**Comment by brandonscript** [comment]
Phew! Thankfully it appears that somehow I ended up adding the subproject as a dependency of itself, without a package.json, and it's blowing up. Haven't fixed it yet, but definitely not caused by subgrunt.

👍

**Comment by tusbar** [comment]
👍 glad you found out.
