### ISSUE TITLE
Support for yarn

### ISSUE THREAD

**Issue by LoveIsGrief** [tusbar/grunt-subgrunt#55]
[Yarn](https://yarnpkg.com/) is a new dependency manager, which has better performance than npm and is supposed to be able to be used as a drop-in replacement. It would be great to have this supported :)

Cheers

**Comment by tusbar** [comment]
Hey @LoveIsGrief,

Thanks for the suggestion, yeah, that sounds nice, something like a `pm` or `packageManager` option that defaults to `npm`.

**Comment by tusbar** [comment]
@LoveIsGrief today you can use 

```
task: {
    options: {
        npmPath: 'yarn'
    },
    projects: [
        'path/to/project'
    ]
},
```

**Comment by LoveIsGrief** [comment]
ha ha, yep, indeed it should! Maybe just renaming or aliasing `npmPath` as the name you suggested would be great. I guess you can label this as low priority :)
